inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'bin/*'
  NewCops: disable

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false