default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # url: <%= ENV["DATABASE_URL"] %>
  # port: 5439

development:
  <<: *default
  database: alljobs_development

test:
  <<: *default
  # database: alljobs_test
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
