default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: alljobs_development

test:
  <<: *default
  # database: alljobs_test
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  primary:
    <<: *default
    database: alljobs_production
    username: alljobs
    password: <%= ENV['ALLJOBS_DATABASE_PASSWORD'] %>
  queue:
    <<: *default
    database: alljobs_production_queue
    migrations_paths: db/queue_migrate

