default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5433 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: alljobs_development

test:
  <<: *default
  database: alljobs_test

production:
  primary:
    <<: *default
    host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
    database: alljobs_production
    username: <%= ENV["DATABASE_USER"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
  queue:
    <<: *default
    host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
    database: alljobs_production_queue
    username: <%= ENV["DATABASE_USER"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    migrations_paths: db/queue_migrate
