default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # url: <%= ENV["DATABASE_URL"] %>
  # port: 5439

development:
  <<: *default
  database: alljobs_development

test:
  <<: *default
  database: alljobs_test
  password: password

production:
  <<: *default
  database: alljobs_production
  username: alljobs
  password: <%= ENV['ALLJOBS_DATABASE_PASSWORD'] %>
