name: Rspec and Rubocop CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POSTGRES_DB: alljobs_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  test:
    name: Lint and tests
    environment: alljobs
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_DB: alljobs_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -yqq install libpq-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Ruby dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Analyze code
        run: bundle exec rubocop

      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          DISABLE_SPRING: 1
        run: |
          bundle exec rails db:schema:load
          bundle exec rspec --format progress

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
